spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  web:
    resources:
      static-locations: # quickhack to facilitate static development
        - file:src/main/resources/static/
        - classpath:/static/
app:
  security:
    jwt:
      keystore-location: "keys/keystore.jks"
      keystore-password: "password"
      key-alias: "jwtsigning"
      private-key-passphrase: "password"
logging:
  pattern:
    dateformat: HH:mm:ss
  level:
    # root: TRACE
    org:
      springframework:
        beans:
          factory:
            support:
              DefaultListableBeanFactory: INFO
      apache:
        tomcat:
          util:
            net:
              NioEndpoint: INFO
    sun:
      rmi: INFO
  endpoints:
    web:
      exposure:
        include: '*'
