# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Install Nix
      uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check nix flake
      run: nix flake check
    - name: Run tests
      # We're not using nix build, this is a gradle project.
      run: nix develop --command bash -c './gradlew test'
    - uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
      with:
        name: reports
        path: build/reports